/**
 * DailyReflectionCard — the smallest possible Premium AI surface on Home.
 *
 * Not a new navigation destination, not a chat, not the primary thing on
 * the screen — a small, secondary card below the existing content. Renders
 * nothing at all (no spinner, no error banner) while loading or when no
 * reflection is available; per spec, "unavailable" must read as absence,
 * never as a scary error. useDailyReflection() already collapses every
 * failure mode (premium gate, AI provider down, invalid output) into the
 * same "nothing to show" state, so this component never needs to know why.
 *
 * Every string rendered here is exactly what the backend returned —
 * summary/observations/suggestion straight from Qwen (already validated
 * and Persian-checked server-side), and the trailing disclaimer line is
 * backend-appended, not generated by this component.
 */
import React, { memo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useTheme } from '@hooks/useTheme';
import { Card, Icon } from '@components/ui';
import { useDailyReflection } from '@hooks/queries/useDailyReflection';

export const DailyReflectionCard = memo(function DailyReflectionCard() {
  const { reflection } = useDailyReflection();
  const { colors, spacing, typography, borderRadius } = useTheme();

  if (!reflection) {
    return null;
  }

  return (
    <Card
      rounded="2xl"
      style={[
        styles.card,
        {
          borderColor: colors.infoBorder,
          backgroundColor: colors.surface,
          padding: spacing[5],
        },
      ]}
    >
      <View style={styles.header}>
        <View
          style={[
            styles.badge,
            {
              backgroundColor: colors.infoBg,
              borderColor: colors.infoBorder,
              borderWidth: 1,
              borderRadius: borderRadius.pill,
            },
          ]}
        >
          <Icon name="creation" size={14} color={colors.info} />
          <Text style={{ color: colors.info, fontSize: typography.caption, fontWeight: '700' }}>
            بازتاب هوشمند
          </Text>
        </View>
      </View>

      <Text
        style={{
          color: colors.textPrimary,
          fontSize: typography.bodySmall,
          lineHeight: 22,
          fontWeight: '600',
          marginTop: spacing[3],
        }}
      >
        {reflection.summary}
      </Text>

      {reflection.observations.length > 0 && (
        <View style={[styles.observationsBox, { marginTop: spacing[2] }]}>
          {reflection.observations.map((obs, i) => (
            <View key={i} style={styles.bulletRow}>
              <View style={[styles.bulletDot, { backgroundColor: colors.info }]} />
              <Text
                style={{
                  flex: 1,
                  color: colors.textSecondary,
                  fontSize: typography.caption,
                  lineHeight: 20,
                }}
              >
                {obs}
              </Text>
            </View>
          ))}
        </View>
      )}

      {reflection.suggestion ? (
        <View
          style={[
            styles.suggestionBox,
            {
              backgroundColor: colors.surfaceSecondary,
              borderRadius: borderRadius.md,
              padding: spacing[3],
              marginTop: spacing[3],
            },
          ]}
        >
          <Text
            style={{
              color: colors.textPrimary,
              fontSize: typography.bodySmall,
              fontWeight: '600',
              lineHeight: 20,
            }}
          >
            {reflection.suggestion}
          </Text>
        </View>
      ) : null}

      {reflection.limitations.map((lim, i) => (
        <Text
          key={i}
          style={{
            color: colors.textTertiary,
            fontSize: typography.micro,
            lineHeight: 16,
            marginTop: spacing[2],
          }}
        >
          {lim}
        </Text>
      ))}
    </Card>
  );
});

const styles = StyleSheet.create({
  card: { overflow: 'hidden' },
  header: { flexDirection: 'row', alignItems: 'center' },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 4 },
  observationsBox: { gap: 6 },
  bulletRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  bulletDot: { width: 5, height: 5, borderRadius: 2.5, marginTop: 7 },
  suggestionBox: {},
});
