/**
 * DailyReflectionCard — the smallest possible Premium AI surface on Home.
 *
 * Not a new navigation destination, not a chat, not the primary thing on
 * the screen — a small, secondary card below the existing content. Renders
 * nothing at all (no spinner, no error banner) while loading or when no
 * reflection is available; per spec, "unavailable" must read as absence,
 * never as a scary error. useDailyReflection() already collapses every
 * failure mode (premium gate, AI provider down, invalid output) into the
 * same "nothing to show" state, so this component never needs to know why.
 *
 * Every string rendered here is exactly what the backend returned —
 * summary/observations/suggestion straight from Qwen (already validated
 * and Persian-checked server-side), and the trailing disclaimer line is
 * backend-appended, not generated by this component.
 */
import React, { memo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useTheme } from '@hooks/useTheme';
import { Card, Icon } from '@components/ui';
import { useDailyReflection } from '@hooks/queries/useDailyReflection';

export const DailyReflectionCard = memo(function DailyReflectionCard() {
  const { reflection } = useDailyReflection();
  const { colors, spacing, typography, borderRadius } = useTheme();

  if (!reflection) {
    return null;
  }

  return (
    <Card style={[styles.card, { padding: spacing[4], marginBottom: spacing[4] }]}>
      <View style={styles.header}>
        <View
          style={[
            styles.badge,
            { backgroundColor: colors.premiumBg, borderRadius: borderRadius.pill },
          ]}
        >
          <Icon name="creation" size={12} color={colors.premium} />
          <Text style={{ color: colors.premium, fontSize: typography.caption, fontWeight: '700' }}>
            بازتاب هوشمند
          </Text>
        </View>
      </View>

      <Text
        style={{ color: colors.textPrimary, fontSize: typography.bodySmall, lineHeight: 22, marginTop: spacing[2] }}
      >
        {reflection.summary}
      </Text>

      {reflection.observations.map((obs, i) => (
        <Text
          key={i}
          style={{ color: colors.textSecondary, fontSize: typography.caption, lineHeight: 20, marginTop: spacing[1] }}
        >
          {`· ${obs}`}
        </Text>
      ))}

      {reflection.suggestion ? (
        <Text
          style={{
            color: colors.textPrimary,
            fontSize: typography.bodySmall,
            fontWeight: '600',
            marginTop: spacing[3],
          }}
        >
          {reflection.suggestion}
        </Text>
      ) : null}

      {reflection.limitations.map((lim, i) => (
        <Text
          key={i}
          style={{ color: colors.textTertiary, fontSize: typography.caption, lineHeight: 18, marginTop: spacing[2] }}
        >
          {lim}
        </Text>
      ))}
    </Card>
  );
});

const styles = StyleSheet.create({
  card: { borderWidth: 0 },
  header: { flexDirection: 'row' },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 4 },
});
